name: TipXMR Develop Instance
on:
  push:
    branches:
      - develop
      - develop_deploy
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_TIPXMR_SERVER }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.TIPXMR_SERVER_HOST }}
          REMOTE_USER: ${{ secrets.TIPXMR_SERVER_USER }}
          REMOTE_PORT: ${{ secrets.TIPXMR_SERVER_SSH_PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET_PATH_DEVELOP }}
          EXCLUDE: "/dist/, /node_modules/"
